### ISSUE TITLE
Sign up + Account Tracking Database - Kian

### ISSUE THREAD

**Issue by hetvit27** [hetvit27/team9trimester2#6]
- [x] Create frontend to map out idea
- [ ] Create backend + Deploy via AWS
- [ ] Create update/delete API for backend
- [ ] Link all to frontend
- [ ] Organize page and make it look aesthetic
- [ ] Focus on security
